repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff check --fix
        language: system
        types: [python]
      - id: ty
        name: ty type checker
        entry: uv run ty check
        language: system
        types: [python]
      - id: pyrefly
        name: pyrefly static analyzer
        entry: uv run pyrefly check
        language: system
        types: [python]
      - id: mypy
        name: mypy type checker
        entry: uv run mypy
        language: system
        types: [python]
      - id: pyright
        name: pyright type checker
        entry: uv run pyright
        language: system
        types: [python]