@echo off
echo Starting test server...
start "Test Report Server" cmd /c "run_server.bat"

echo Waiting for server to start...
timeout /t 2 /nobreak > nul

echo Opening report in browser...
call open_report.bat

echo Running tests...
call run_tests.bat
